plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'expo.modules.sheettts'
version = '1.0.0'
android {
  namespace "expo.modules.sheettts"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
    consumerProguardFiles 'proguard-rules.pro'
  }
  lint { abortOnError false }
  packagingOptions {
    pickFirst '**/libc++_shared.so'
    pickFirst '**/libonnxruntime.so'
  }
}
dependencies {
  implementation 'androidx.core:core-ktx:1.13.1'
  implementation 'org.apache.commons:commons-compress:1.26.1'
}
